databases:
  - name: db # Render PG13
    databaseName: yamato
    user: yamato_user
    postgresMajorVersion: 13

services:
  - type: redis # Render Redis
    name: redis
    ipAllowList: []

  - type: web
    name: web
    env: python
    buildCommand: ...
    startCommand: "python manage.py runserver 0.0.0.0:8000"

  - type: redis # Render Celery Redis
    name: celery-redis
    ipAllowList: []
